### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mikeymike** [php-school/php-workshop#3]
- [x] Initial console menu (with Climate ?)
- [x] Lesson / Task interface
- [x] Lesson / Task validators (default being a simple expects)
- [x] Lesson / Task page, output details
- [x] Lesson / Task runner
- [x] All the tests
- [x] Move SyntaxHighlighter to separate package
- [x] Finish tests for SyntaxHighlighter
- [x] Docs for SyntaxHighlighter 
- [x] Pin php-workshop to php-parser 2.x@beta
- [x] Fix tests (Update usages of php-parser to 2.x)
- [x] Add CLI command parsing (verify, run, help) etc
- [x] Fix mark-down URLS's (don't wrap in curly braces & parse correctly)
- [x] Build output page for task
- [x] Replace variables in markdown files, like `{appname}`
- [x] Markdown code parser should only syntax highlight PHP code
- [ ] Colours do not work on Windows
- [x] Pass terminal width in HorizontalRuleRenderer
- [x] E2E tests for MD Parser & Syntax Highlighter
- [x] Tag versions of psx & cli-md-renderer
- [x] Make it possible to add other language parsers to code-fence renderer
- [x] Update docs for custom highlighters to MD Renderer
- [x] Help command
- [x] Help Menu
- [x] Credits Menu

![Welcome!](http://www.reactiongifs.com/r/wtfs.gif)
